[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.312/platform-espressif32.zip
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    bblanchon/ArduinoJson@7.4.3
    ESP32Async/ESPAsyncWebServer@3.11.2
    ESP32Async/AsyncTCP@3.5.0